version: '3.9'

services:
    nginx:
        build: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - ./app:/app
        restart: on-failure

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./app:/app
        restart: on-failure

    php-cli:
        build: docker/php-cli
        user: "1000:1000"
        volumes:
            - ./app:/app
        restart: on-failure

    mysql:
        image: mysql:8.0.31
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: mysql
        ports:
            - "5000:80"